version: "3"

services:
  to_do_app:
    container_name: to_do_app
    build: ./
    image: to_do_app
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /src/to_do_app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/src/to_do_app