# Generated by Django 3.0.7 on 2020-06-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_id',
            field=models.CharField(default='deafult', max_length=50),
            preserve_default=False,
        ),
    ]
